# fly.toml app configuration file generated for black-sea-6942 on 2023-11-04T18:14:15+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "black-sea-6942"
primary_region = "mad"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
